alt_flag_conflict_mode: pixel_confidence
alt_flag_conflict_stu_use_more: false
alt_flag_epoch_shuffle_teachers: false
alt_flag_updating_period_random: true
alt_param_conflict_weight: 1.0
alt_param_ensemble_temp: 1.0
alt_param_threshold_self_training: 0.95
alt_param_updating_period_iters: 50
base_lr: 0.01
batch_size: 24
conf_threshold: 0.95
consistency: 2.0
consistency_rampup: 50
copy_paste_prob: 0.0
cutmix_prob: 1.0
ema_decay: 0.99
flag_sampling_based_on_lb: false
flag_ulb_loss_type: dice
labeled_bs: 12
labeled_num: 44
max_iterations: 30000
model: unet
num_classes: 2
poly: true
res_path: c:/ai-agent/repo/AD-MT/results
root_path: c:/ai-agent/repo/AD-MT/data/Kvasir
seed: 2023
test_interval_ep: 2
